### PR TITLE
Neovim parity

### LINKED ISSUE #42: Sync rendering of jsonrpc notifications with neovim
We have 6 different jsonrpc notification methods which must each have a rendering function.

* `start`
* `message`
* `functions`
* `functions-done`
* `prompts`
* `error`

We are writing this content into a markdown buffer.  In neovim, a treesitter plugin is always updating the treesitter AST as the buffer changes, and this allows a `highlight` module to create syntax highlighting for different sections (different roles), code fences, and errors.  I think this makes it easier to distinguish the different.

If vscode can not use treesitter for this, we can add semantic tokens to the LSP to get the same effect - I assume vscode can have different color schemes based on the LSP semantic tokens. In practice, I find the default treesitter implementation in neovim to be good enough so if we add semantic tokens, it'd only be to support special syntax highlighting in vscode.  @ColinMcNeil to find out what vscode requires.

None of the methods should put their json params directly into the buffer.

* the `start` method params have fields `level` `role` and `content`.  WE should be creating headers (#, ##, ###, etc) depending on the `level`.  The title should be `ROLE {{role}} ({{content}}).  Note that the content is shown in round brackets.

* the 'message' method just indicates that you should append either the `content` or the `debug` message into the buffer (`debug` only if debug mode is toggled on)

* the `functions` method always has json content and should append from a range.  The content should be in a json fenced code block at all times.

* the `functions-done` is just sent to allow the function to be written one last time and add a new line.

* the `error` method has two params `content` and `exception`. I would suggest that we show only `content` for now. The content should be in a codeblock with a language of error.

```error
content from error
```
This will allow us to highlight this codeblock with a red color to indiciate an error.

### PR DESCRIPTION
**Pull request by ColinMcNeil**
Resolves #42 

New functions
-   start
-   message
-   functions
-   functions-done
-   prompts
-   error

### CODE REVIEW

File: src/commands/runPrompt.ts [hunk 1]
```diff
@@ -168,42 +168,54 @@ export const runPrompt: (secrets: vscode.SecretStorage, mode: PromptOption) => v
...
+                    break;
+                case 'prompts':
+                    const promptHeader = '# Rendered Prompt\n\n';
+                    if (!doc.getText().includes(promptHeader)) {
+                        await writeToEditor(promptHeader);
+                    }
+                    await writeToEditor(json.params.messages.map((m: any) => JSON.stringify(m, null, 2)).join('\n') + '\n');
+                    break;
+                case 'error':
+                    await writeToEditor('```error\n' + (json.params.content as Error).toString() + '\n```');
```
Comment (slimslenderslacks) [inline src/commands/runPrompt.ts]: will you need an other line break at the end of this?

File: src/commands/runPrompt.ts [hunk 2]
```diff
@@ -168,42 +168,54 @@ export const runPrompt: (secrets: vscode.SecretStorage, mode: PromptOption) => v
...
+                    const { level, role, content } = json.params;
+                    const header = Array(level).fill('#').join('');
+                    await writeToEditor(`${header} ROLE ${role} (${content})\n`);
+                    break;
+                case 'functions-done':
+                    await writeToEditor(json.params.content);
+                    break;
+                case 'message':
+                    await writeToEditor(json.params.content);
+                    if (json.params.debug) {
```
Comment (slimslenderslacks) [inline src/commands/runPrompt.ts]: I feel like this can't be right because `message` notifications can also have `content`.  And the `debug` messages should only be shown when we're in debug mode.  Otherwise, this is just streaming content from the assistant.  I haven't tried this but it feels like it must not work just looking at the code.

File: src/commands/runPrompt.ts [hunk 3]
```diff
@@ -168,42 +168,54 @@ export const runPrompt: (secrets: vscode.SecretStorage, mode: PromptOption) => v
...
+                        const params_str = args;
+                        let functionRange = ranges[id] || getBaseFunctionRange();
+                        if (functionRange.isSingleLine) {
+                            // Add function to the end of the file and update the range
+                            await writeToEditor(params_str);
+                            functionRange = new vscode.Range(functionRange.start.line, functionRange.start.character, doc.lineCount, 0);
+                        }
+                        else {
+                            // Replace existing function and update the range
+                            await writeToEditor(params_str, functionRange);
```
Comment (slimslenderslacks) [inline src/commands/runPrompt.ts:184]: Did you put these functions into code fences?

**Review by slimslenderslacks — CHANGES_REQUESTED** [review]
With the latest of vonwig/prompts:latest, we should be able to try this and verify that it looks right.

File: src/commands/runPrompt.ts (hunk 3 above)
Comment (ColinMcNeil) [reply src/commands/runPrompt.ts:184]: TODO

File: src/commands/runPrompt.ts (hunk 2 above)
Comment (ColinMcNeil) [reply src/commands/runPrompt.ts]: I haven't implemented the debug mode or colors yet.
