### PR TITLE
Fix unhelpful errors while generating runbooks.

### LINKED ISSUE #21: Missing Docker Engine error is hard to interpret
Reproduction

1. Stop Docker engine
2. Start VScode
3. Choose "Generate runbook"

CleanShot 2024-06-10 at 17 20 30

Can this be something closer to "No local Docker Engine detected" just so we can be more prescriptive.

### PR DESCRIPTION
**Pull request by ColinMcNeil**
Resolves #21

### CODE REVIEW

File: src/commands/generateRunbook.ts [hunk 1]
```diff
@@ -50,15 +50,24 @@ const prepareRunbookFile = async (workspaceFolder: vscode.WorkspaceFolder, promp
...
         }
-    } catch (e) {
-        return vscode.window.showErrorMessage("Docker not found", { modal: true }, "Install Docker Desktop").then((value) => {
+
+        if (res.status !== 0) {
+            throw new Error(`Docker command exited with code ${res.status} and output the following error: ${res.error || res.stderr.toString()}`);
+        }
+
+    } catch (e: unknown) {
+        return vscode.window.showErrorMessage("Error starting Docker", { modal: true, detail: (e as Error).toString() }, "Install Docker Desktop", "Try again").then((value) => {
```
Comment (slimslenderslacks) [inline src/commands/generateRunbook.ts]: This code looks to me like you're going to recommend installing Docker Desktop even in cases where the engine is just down.  You are able to resolve the difference between the docker cli available and the docker cli being present but the docker engine not running.

File: src/commands/generateRunbook.ts [hunk 2]
```diff
@@ -50,15 +50,24 @@ const prepareRunbookFile = async (workspaceFolder: vscode.WorkspaceFolder, promp
...
             if (value === "Install Docker Desktop") {
                 vscode.env.openExternal(vscode.Uri.parse("https://www.docker.com/products/docker-desktop"));
             }
+            else if (value === "Try again") {
```
Comment (slimslenderslacks) [inline src/commands/generateRunbook.ts]: Would it be a good idea to recommend installing docker desktop only if the docker cli is really not present, and then have "try again after starting the docker engine" if it's just a matter of doing that.  I wonder if there's a cli tool to start the docker engine.  :)

**Review by slimslenderslacks — CHANGES_REQUESTED** [review]
I'm assuming that if the docker executable can not be found, then spawnSync returns a res with a nil status but with an error that somehow indicates that this process could not be started.

File: src/commands/generateRunbook.ts (hunk 2 above)
Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: > wonder if there's a cli tool to start the docker engine

Somewhat platform dependent, but something to try.

File: src/commands/generateRunbook.ts (hunk 1 above)
Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: >recommend installing Docker Desktop even in cases where the engine is just down

Yeah, that was the idea. We can make this modal more actionable with some changes.

Comment (slimslenderslacks) [reply src/commands/generateRunbook.ts]: I just don't think we should recommend re-installing docker desktop when it's likely just that the docker engine is not running.  I think that's just wrong because it makes it seem like Docker Desktop is somehow broken but it's just  ... not running.

File: src/commands/generateRunbook.ts (hunk 2 above)
Comment (slimslenderslacks) [reply src/commands/generateRunbook.ts]: Good point.  There might be some platform dependent things here.  I think darwin and linux will turn out to be the same but we need to verify that wsl2 is the same.

I just think it's wrong to ask users to even suggest re-installing Docker Desktop when the engine is just not running.

Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: I committed something which works in OSX, and should work on windows but I'll be testing that soon. You can try linux?

File: src/commands/generateRunbook.ts (hunk 1 above)
Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: Alright, this change is committed.

File: src/commands/generateRunbook.ts [hunk 3]
```diff
@@ -49,15 +55,35 @@ const prepareRunbookFile = async (workspaceFolder: vscode.WorkspaceFolder, promp
...
-            if (value === "Install Docker Desktop") {
-                vscode.env.openExternal(vscode.Uri.parse("https://www.docker.com/products/docker-desktop"));
+
+        dockerExists = true;
+
+        if (res.status !== 0) {
+            throw new Error(`Docker command exited with code ${res.status} and output the following error: ${res.error || res.stderr.toString()}`);
+        }
+
+    } catch (e: unknown) {
```
Comment (slimslenderslacks) [inline src/commands/generateRunbook.ts]: Normally, I would say this looks like a job for typed exceptions.  It's hard to see from this code that `dockerExists` is being used as a signal into the catch handler that the exception was thrown because of a process that property exited.

File: src/commands/generateRunbook.ts [hunk 4]
```diff
@@ -49,15 +55,35 @@ const prepareRunbookFile = async (workspaceFolder: vscode.WorkspaceFolder, promp
...
+        const platform = process.platform;
+        const actionItems = dockerExists ? [(platform in START_DOCKER_COMMAND ? "Start Docker & Retry" : "Try again")] : ["Install Docker Desktop", "Try again"];
+        return vscode.window.showErrorMessage("Error starting Docker", { modal: true, detail: (e as Error).toString() }, ...actionItems).then(async (value) => {
+            switch (value) {
+                case "Start Docker & Retry":
+                    spawnSync(START_DOCKER_COMMAND[platform as keyof typeof START_DOCKER_COMMAND], { shell: true });
+                    // Wait 4 seconds for docker to start up
+                    await new Promise((resolve) => setTimeout(resolve, 4000));
```
Comment (slimslenderslacks) [inline src/commands/generateRunbook.ts]: Cool idea that you might be able to get these services up if they choose this.  But the loop to detect whether or not the engine is ready is harder than this, right?  Should we start by just asking them to do this and come back when it's ready?  Otherwise aren't we just back in this loop again after docker.make-runbook.generate fails a second time?

File: src/commands/generateRunbook.ts [hunk 5]
```diff
@@ -13,6 +13,12 @@ const ENDPOINT_ENUM_MAP = {
     Ollama: "http://localhost:11434/v1"
 };
 
+const START_DOCKER_COMMAND = {
+    'win32': 'Start-Process -NoNewWindow -Wait -FilePath "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe"',
+    'darwin': 'open -a Docker',
+    'linux': 'docker',
```
Comment (slimslenderslacks) [inline src/commands/generateRunbook.ts]: I don't think this is right for `linux`.

Comment (slimslenderslacks) [reply src/commands/generateRunbook.ts]: For OSS linux, the docker daemon is normally not managed by a user space process.

File: src/commands/generateRunbook.ts (hunk 3 above)
Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: I made my own exception type for this

**Review by slimslenderslacks — CHANGES_REQUESTED** [review]
Comments in slack - my opinion is that automating "start docker and retry" has to be really solid to be worth including.  Otherwise, you should keep this simple.

File: src/commands/generateRunbook.ts (hunk 5 above)
Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: Switched to `systemctl --user start docker-desktop` which should work more often

File: src/commands/generateRunbook.ts (hunk 4 above)
Comment (ColinMcNeil) [reply src/commands/generateRunbook.ts]: Removed

**Review by slimslenderslacks — APPROVED** [review]
